# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 683adb8327f0fdbe91134cad19ba43a6708e6ec7fff1b25a78f63a4e864158676261ae0bdcdd3b24ec1ec6247a24f9bda3885a496499737fc2a3414bc468d456

test:
  secret_key_base: 1c4407df7e31d5d29b63f8b52584342824ec2f92611a0e296f99d9be9ac613dfebfbaf797208c524fe5c9f3cf252a5a93db69ae17b0c631ca27df50c9db1dbec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
